config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :houses do
    resources :comments
  end
  root 'welcom#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :house
end

app/models/house.rb
class House < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 5}
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @house = House.find(params[:house_id])
        @comment = @house.comments.create(comment_params)
        redirect_to house_path(@house)
    end
    
    def destroy
        @house = House.find(params[:house_id])
        @comment = @house.comments.find(params[:id])
        @comment.destroy
        redirect_to house_path(@house)
    end
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
        
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:title, :category, :address, :deposit, :fee, :image, :description)
    end
end

app/controllers/welcom_controller.rb
class WelcomController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, ['Apartment' ,'One room', 'Homestay'] %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :deposit %><br>
    <%= f.number_field :deposit %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.number_field :fee %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          
            <% if user_signed_in? %>
            <%= current_user.email %>
            <a class="navbar-brand" href="/users/sign_out">LOGOUT</a>
            <% else %>
            <a class="navbar-brand" href="/users/sign_in">LOGIN</a>
            <% end %>
            
            
          
          
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/" target="_self">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <% if user_signed_in? %>
                <a class="nav-link" href="../houses/new" target="_self">Link</a>
                <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        

<p id="notice"><%= notice %></p>

<h1>House list</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Address</th>
      <th>Deposit</th>
      <th>Fee</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.title %></td>
        <td><%= house.category %></td>
        <td><%= house.address %></td>
        <td><%= house.deposit %></td>
        <td><%= house.fee %></td>
        <td><%= house.description %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          
            <% if user_signed_in? %>
            <%= current_user.email %>
            <a class="navbar-brand" href="/users/sign_out">LOGOUT</a>
            <% else %>
            <a class="navbar-brand" href="/users/sign_in">LOGIN</a>
            <% end %>
            
            
          
          
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <% if user_signed_in? %>
                <a class="nav-link" href="../houses/new" target="_self">Link</a>
                <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>

<div class="container-fluid fiil height" style="text-align: center;">
    <h1>New House</h1>
    <%= render 'form' %>
    <%= link_to '리스트', houses_path %>
</div>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @house.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @house.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @house.deposit %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @house.fee %>
</p>

<p>
  <strong>Image:</strong>
  <%= @house.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @house.description %>
</p>

<h3>Comments</h3>
<% @house.comments.each do |comment| %>
  <p>
    <strongCommenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strongCommente:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to 'Destroy Comment', [comment.house, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>


<h3>Add a comment:</h3>
<%= form_for([@house, @house.comments.build]) do |f| %>
  <p>
      <%=f.label :commenter %><br>
      <%=f.text_field :commenter %><br>
  </p>
  <p>
      <%=f.label :body %><br>
      <%=f.text_area :body %><br>
  </p>  
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<br>
<%- if controller_name != 'sessions' %>
  <%= link_to '<button type="button" class="btn btn-success">로그인</button>'.html_safe, new_session_path(resource_name) %><br />
<% end -%>
<br>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to '<button type="button" class="btn btn-success">회원가입</button>'.html_safe, new_registration_path(resource_name) %><br />
<% end -%>
<br>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to '<button type="button" class="btn btn-success">비밀번호찾기</button>'.html_safe, new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcom/index.html.erb
<head>
  <link href='http://fonts.googleapis.com/earlyaccess/nanumbrushscript.css' rel='stylesheet' type='text/css' />
  <style>
  #footer{
    display: table;
    text-align: light;
    margin-left: auto;
    margin-right: auto;
}
#ti{
  font-family: ‘Nanum Brush Script’, Helvetica, Arial, sans-serif;
}

    
  </style>

</head>  
<body>
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          
            <% if user_signed_in? %>
            <%= current_user.email %>
            <a class="navbar-brand" href="/users/sign_out">LOGOUT</a>
            <% else %>
            <a class="navbar-brand" href="/users/sign_in">LOGIN</a>
            <% end %>
            
            
          
         
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <% if user_signed_in? %>
                <a class="nav-link" href="../houses/new" target="_self">Link</a>
                <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        
    
        <div class="jumbotron">
          <h1 class="display-3" id="ti" >다 방 구</h1>
         
          <p class="lead">대한민국에서 가장 간단한 집계약 웹 사이트 입니다.</p>
          <hr class="my-4">
          <p>The simplest house contract website in Korea.</p>
 
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <img src="place1.JPG" class="rounded float-left" width="300" height="300" alt="place1">
                </div>
                <div class="col-sm-6 col-md-3">
                     <img src="place2.JPG" class="rounded float-right" width="300" height="300" alt="place2">
                </div>
                
                <div class="col-md-3 col-md-3">
                     <img src="place3.JPG" class="rounded float-left" width="300" height="300" alt="place3">
                </div>
                <div class="col-md-3 col-md-3">
                     <img src="place4.JPG" class="rounded float-right" width="300" height="300" alt="place4">
                </div>
            </div>

        </div>
        </br>
        
        <footer class="container">
            <div class="row">
                <div class="span12">

                    <p class="copyright">&copy; made by jiyeon</p>
                    <p class="copyright">문제가 있을 시 연락 주세요. 010-7405-0522</p>

                </div>
            </div>
        </footer>
        
</body>